# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://icanread.io
title: I Can Read
email: info@icanread.io
author: Adam Gustavsson
description: > # "Write an awesome description for your new site here. 
  ICanLearn is a tool that will help people with dyslexia to read. Just point at the text and ICanLearn will read it for you.
copyright: 'Copyright &copy; 2018 ICanRead. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
